version: 2.1

jobs:
  build:
    docker:
      - image: python
    working_directory: ~/repo
    steps:
      - checkout
      - run: python scripts/ci/install
      - run: python scripts/ci/run-test

# vim: et sw=2 ts=2
